name: Build presentations

on:
  push:
    branches: ["main"]
    paths:
      - "git-advanced/presentation/content/*.md"
      - "gitlab-ci/presentation/content/**.md"

permissions:
  contents: read

jobs:
  merge-source-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.in-project true
      - name: Install dependencies
        working-directory: tools/merge
        run: poetry install
      - name: Merge source files
        working-directory: tools/merge
        run: |
          poetry run python merge.py ../../git-advanced/presentation/config.json
          poetry run python merge.py ../../gitlab-ci/presentation/config.json
      - name: Store merged files
        uses: actions/upload-artifact@v4
        with:
          name: merged-files
          retention-days: 1
          path: |
            git-advanced/presentation/content/output/git-advanced.md
            gitlab-ci/presentation/jour-1/output/gitlab-ci-jour-1.md
            gitlab-ci/presentation/jour-2/output/gitlab-ci-jour-2.md

  build:
    runs-on: ubuntu-latest
    needs: merge-source-files
    steps:
      - uses: actions/checkout@v4
      - name: Get Marp CLI
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "marp-team/marp-cli"
          fileName: "marp-cli-*-linux.tar.gz"
          latest: true
          extract: true
      - name: Download merged files
        uses: actions/download-artifact@v4
        with:
          name: merged-files
      - name: Generate HTML files
        run: |
          ./marp -I git-advanced/presentation/content/output --allow-local-files --output _site
          ./marp -I gitlab-ci/presentation/jour-1/output --allow-local-files --output _site
          ./marp -I gitlab-ci/presentation/jour-2/output --allow-local-files --output _site
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
