name: Build presentations PDFs

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  merge-source-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: poetry install
      - name: Merge source files
        run: |
          poetry run python merge.py ./git-advanced/presentation/config.json
          poetry run python merge.py ./gitlab-ci/presentation/config.json
      - name: Store merged files
        uses: actions/upload-artifact@v4
        with:
          name: merged-files
          retention-days: 1
          path: |
            git-advanced/presentation/content/prez.md
            gitlab-ci/presentation/jour-1/jour-1.md
            gitlab-ci/presentation/jour-2/jour-2.md
