name: Build presentations

on:
  push:
    branches: ["main"]
    paths:
      - "git-advanced/presentation/content/*.md"
      - "gitlab-ci/presentation/content/**.md"
      - ".github/workflows/build-prez.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  merge-source-files:
    strategy:
      matrix:
        include:
          - name: merge-git-advanced
            source-config-path: git-advanced/presentation/config.json
            output-path: git-advanced/presentation/dist/
          - name: merge-gitlab-ci
            source-config-path: gitlab-ci/presentation/config.json
            output-path: gitlab-ci/presentation/dist/
    uses: ./.github/workflows/merge-sources-files.yml
    name: ${{ matrix.name }}
    with:
      source-config-path: ${{ matrix.source-config-path }}
      output-path: ${{ matrix.output-path }}
    secrets: inherit

  build-marp:
    runs-on: ubuntu-latest
    needs: merge-source-files
    steps:
      - uses: actions/checkout@v4
      - name: Get Marp CLI
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "marp-team/marp-cli"
          fileName: "marp-cli-*-linux.tar.gz"
          latest: true
          extract: true
      - name: Download merged files
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist/
      - name: Generate HTML files
        run: |
          ./marp -I dist/ --allow-local-files --output _site --html
      - name: Store built files
        uses: actions/upload-artifact@v4
        with:
          name: marp-builds
          retention-days: 1
          path: _site/*.html

  build-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.in-project true
      - name: Install dependencies
        working-directory: tools
        run: poetry install
      - name: Generate index.html file
        working-directory: tools
        run: |
          poetry run python cli.py template \
            -d ../_site \
            -c ../git-advanced/presentation/config.json \
            -c ../gitlab-ci/presentation/config.json
      - name: Store built file
        uses: actions/upload-artifact@v4
        with:
          name: index-build
          retention-days: 1
          path: _site/index.html

  build-pages:
    runs-on: ubuntu-latest
    needs:
      - build-index
      - build-marp
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: _site/
          pattern: "*-build*"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build-pages
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
