name: Merge source files

on:
  workflow_call:
    inputs:
      source-config-path:
        required: true
        type: string
      output-path:
        required: true
        type: string

permissions:
  contents: read

jobs:
  merge-source-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.in-project true
      - name: Install dependencies
        working-directory: tools/merge
        run: poetry install
      - name: Merge source files
        run: |
          poetry run python tools/merge/merge.py ${{ inputs.source-config-path }}
      - name: Store merged files
        uses: actions/upload-artifact@v4
        with:
          name: merged-artifact-${{ hashFiles(inputs.source-config-path) }}
          retention-days: 1
          path: ${{ inputs.output-path }}
