name: Build and release PDF

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  merge-source-files:
    strategy:
      matrix:
        include:
          - name: merge-git-advanced
            source-config-path: git-advanced/presentation/config.json
            output-path: git-advanced/presentation/dist/
          - name: merge-gitlab-ci
            source-config-path: gitlab-ci/presentation/config.json
            output-path: gitlab-ci/presentation/dist/
    uses: ./.github/workflows/merge-sources-files.yml
    name: ${{ matrix.name }}
    with:
      source-config-path: ${{ matrix.source-config-path }}
      output-path: ${{ matrix.output-path }}
    secrets: inherit

  build-pdf:
    runs-on: ubuntu-latest
    needs: merge-source-files
    steps:
      - uses: actions/checkout@v4
      - name: Get Marp CLI
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "marp-team/marp-cli"
          fileName: "marp-cli-*-linux.tar.gz"
          latest: true
          extract: true
      - name: Download merged files
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist/
      - name: Generate PDF files
        run: |
          ./marp -I dist/ --allow-local-files --pdf --html
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-pdfs
          retention-days: 1
          path: dist/*.pdf

  release-pdfs:
    runs-on: ubuntu-latest
    needs: build-pdf
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download built PDFs
        uses: actions/download-artifact@v4
        with:
          name: generated-pdfs
      - name: Release generated PDF
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
        run: |
          gh release create $VERSION ./dist/*.pdf' \
